# Generated by Django 4.2.11 on 2024-03-06 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(default=None, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('logged_out_at', models.DateTimeField(default=None, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('social', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], max_length=20)),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('auth_time', models.DateTimeField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'user_sessions',
            },
        ),
    ]
